apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-web-app
  template:
    metadata:
      labels:
        app: apache-web-app
    spec:
      containers:
      - name: apache-web-app
        image: localhost/devops@sha256:467607e2482f819ec63198262f808f9e46501a04e1e045f1588465dc0acde691
        ports:
        - containerPort: 80
