apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-web-app
  name: apache-deployment
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-web-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

